config/routes.rb
Ruleof72::Application.routes.draw do
  root to: "investments#index"
  resources :investments

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  attr_accessible :interestrate, :principle, :years
  def result
	  ytod = 72.0 / interestrate
	  exp = years / ytod
	  multiplier = 2 ** exp
	  result = principle * multiplier
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @investments }
    end
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
    @investment = Investment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/new
  # GET /investments/new.json
  def new
    @investment = Investment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/1/edit
  def edit
    @investment = Investment.find(params[:id])
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(params[:investment])

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render json: @investment, status: :created, location: @investment }
      else
        format.html { render action: "new" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /investments/1
  # PUT /investments/1.json
  def update
    @investment = Investment.find(params[:id])

    respond_to do |format|
      if @investment.update_attributes(params[:investment])
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment = Investment.find(params[:id])
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_for(@investment) do |f| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% @investment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :principle %><br />
    <%= f.text_field :principle %>
  </div>
  <div class="field">
    <%= f.label :interestrate,"Int Rate" %><br />
    <%= f.text_field :interestrate %>
  </div>
  <div class="field">
    <%= f.label :years %><br />
    <%= f.text_field :years %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<h1>Listing investments</h1>

<table>
  <tr>
    <th>Principle</th>
    <th>Int Rate</th>
    <th>Years</th>
    <th>Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @investments.each do |investment| %>
  <tr>
    <td><%= number_to_currency investment.principle %></td>
    <td><%= number_to_percentage investment.interestrate, precision:1 %></td>
    <td><%= investment.years %></td>
    <td><%= number_to_currency investment.result%></td>
    <td><%= link_to 'Show', investment %></td>
    <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
    <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render 'form' %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Principle:</b>
  <%= @investment.principle %>
</p>

<p>
  <b>Interestrate:</b>
  <%= @investment.interestrate %>
</p>

<p>
  <b>Years:</b>
  <%= @investment.years %>
</p>


<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruleof72</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>